FROM node:12.18.1

ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

#RUN npm install testing-library/react@11.2.5 -g --silent
RUN npm install --production

COPY . .

#CMD [ "npm", "test" ]
RUN npm test
 #--logger:trx --results-directory /src/testresult
