global.tableau = {
  DeviceType: {
    DEFAULT: 'default',
    DESKTOP: 'desktop',
    TABLET: 'tablet',
    PHONE: 'phone',
  },
  DashboardObjectType: {
    BLANK: 'blank',
    WORKSHEET: 'worksheet',
    QUICK_FILTER: 'quickFilter',
    PARAMETER_CONTROL: 'parameterControl',
    PAGE_FILTER: 'pageFilter',
    LEGEND: 'legend',
    TITLE: 'title',
    TEXT: 'text',
    IMAGE: 'image',
    WEB_PAGE: 'webPage',
    ADDIN: 'addIn',
  },
  DataType: {
    FLOAT: 'float',
    INTEGER: 'integer',
    STRING: 'string',
    BOOLEAN: 'boolean',
    DATE: 'date',
    DATETIME: 'datetime',
  },
  DateRangeType: {
    LAST: 'last',
    LASTN: 'lastn',
    NEXT: 'next',
    NEXTN: 'nextn',
    CURR: 'curr',
    TODATE: 'todate',
  },
  ErrorCode: {
    INTERNAL_ERROR: 'internalError',
    SERVER_ERROR: 'serverError',
    INVALID_AGGREGATION_FIELD_NAME: 'invalidAggregationFieldName',
    INVALID_TOOLBAR_BUTTON_NAME: 'invalidToolbarButtonName',
    INVALID_PARAMETER: 'invalidParameter',
    INVALID_URL: 'invalidUrl',
    STALE_DATA_REFERENCE: 'staleDataReference',
    VIZ_ALREADY_IN_MANAGER: 'vizAlreadyInManager',
    NO_URL_OR_PARENT_ELEMENT_NOT_FOUND: 'noUrlOrParentElementNotFound',
    INVALID_FILTER_FIELDNAME: 'invalidFilterFieldName',
    INVALID_FILTER_FIELDVALUE: 'invalidFilterFieldValue',
    INVALID_FILTER_FIELDNAME_OR_VALUE: 'invalidFilterFieldNameOrValue',
    FILTER_CANNOT_BE_PERFORMED: 'filterCannotBePerformed',
    NOT_ACTIVE_SHEET: 'notActiveSheet',
    INVALID_CUSTOM_VIEW_NAME: 'invalidCustomViewName',
    MISSING_RANGEN_FOR_RELATIVE_DATE_FILTERS:
      'missingRangeNForRelativeDateFilters',
    MISSING_MAX_SIZE: 'missingMaxSize',
    MISSING_MIN_SIZE: 'missingMinSize',
    MISSING_MINMAX_SIZE: 'missingMinMaxSize',
    INVALID_SIZE: 'invalidSize',
    INVALID_SIZE_BEHAVIOR_ON_WORKSHEET: 'invalidSizeBehaviorOnWorksheet',
    SHEET_NOT_IN_WORKBOOK: 'sheetNotInWorkbook',
    INDEX_OUT_OF_RANGE: 'indexOutOfRange',
    DOWNLOAD_WORKBOOK_NOT_ALLOWED: 'downloadWorkbookNotAllowed',
    NULL_OR_EMPTY_PARAMETER: 'nullOrEmptyParameter',
    BROWSER_NOT_CAPABLE: 'browserNotCapable',
    UNSUPPORTED_EVENT_NAME: 'unsupportedEventName',
    INVALID_DATE_PARAMETER: 'invalidDateParameter',
    INVALID_SELECTION_FIELDNAME: 'invalidSelectionFieldName',
    INVALID_SELECTION_VALUE: 'invalidSelectionValue',
    INVALID_SELECTION_DATE: 'invalidSelectionDate',
    NO_URL_FOR_HIDDEN_WORKSHEET: 'noUrlForHiddenWorksheet',
    MAX_VIZ_RESIZE_ATTEMPTS: 'maxVizResizeAttempts',
  },
  FieldAggregationType: {
    SUM: 'SUM',
    AVG: 'AVG',
    MIN: 'MIN',
    MAX: 'MAX',
    STDEV: 'STDEV',
    STDEVP: 'STDEVP',
    VAR: 'VAR',
    VARP: 'VARP',
    COUNT: 'COUNT',
    COUNTD: 'COUNTD',
    MEDIAN: 'MEDIAN',
    ATTR: 'ATTR',
    NONE: 'NONE',
    PERCENTILE: 'PERCENTILE',
    YEAR: 'YEAR',
    QTR: 'QTR',
    MONTH: 'MONTH',
    DAY: 'DAY',
    HOUR: 'HOUR',
    MINUTE: 'MINUTE',
    SECOND: 'SECOND',
    WEEK: 'WEEK',
    WEEKDAY: 'WEEKDAY',
    MONTHYEAR: 'MONTHYEAR',
    MDY: 'MDY',
    END: 'END',
    TRUNC_YEAR: 'TRUNC_YEAR',
    TRUNC_QTR: 'TRUNC_QTR',
    TRUNC_MONTH: 'TRUNC_MONTH',
    TRUNC_WEEK: 'TRUNC_WEEK',
    TRUNC_DAY: 'TRUNC_DAY',
    TRUNC_HOUR: 'TRUNC_HOUR',
    TRUNC_MINUTE: 'TRUNC_MINUTE',
    TRUNC_SECOND: 'TRUNC_SECOND',
    QUART1: 'QUART1',
    QUART3: 'QUART3',
    SKEWNESS: 'SKEWNESS',
    KURTOSIS: 'KURTOSIS',
    INOUT: 'INOUT',
    SUM_XSQR: 'SUM_XSQR',
    USER: 'USER',
    COLLECT: 'COLLECT',
  },
  FieldRoleType: {
    DIMENSION: 'dimension',
    MEASURE: 'measure',
    UNKNOWN: 'unknown',
  },
  FilterUpdateType: {
    ALL: 'all',
    REPLACE: 'replace',
    ADD: 'add',
    REMOVE: 'remove',
  },
  FilterType: {
    CATEGORICAL: 'categorical',
    QUANTITATIVE: 'quantitative',
    HIERARCHICAL: 'hierarchical',
    RELATIVEDATE: 'relativedate',
  },
  NullOption: {
    NULL_VALUES: 'nullValues',
    NON_NULL_VALUES: 'nonNullValues',
    ALL_VALUES: 'allValues',
  },
  ParameterAllowableValuesType: {
    ALL: 'all',
    LIST: 'list',
    RANGE: 'range',
  },
  ParameterDataType: {
    FLOAT: 'float',
    INTEGER: 'integer',
    STRING: 'string',
    BOOLEAN: 'boolean',
    DATE: 'date',
    DATETIME: 'datetime',
  },
  PeriodType: {
    YEAR: 'year',
    QUARTER: 'quarter',
    MONTH: 'month',
    WEEK: 'week',
    DAY: 'day',
    HOUR: 'hour',
    MINUTE: 'minute',
    SECOND: 'second',
  },
  SelectionUpdateType: {
    REPLACE: 'replace',
    ADD: 'add',
    REMOVE: 'remove',
  },
  SheetSizeBehavior: {
    AUTOMATIC: 'automatic',
    EXACTLY: 'exactly',
    RANGE: 'range',
    ATLEAST: 'atleast',
    ATMOST: 'atmost',
  },
  SheetType: {
    WORKSHEET: 'worksheet',
    DASHBOARD: 'dashboard',
    STORY: 'story',
  },
  TableauEventName: {
    CUSTOM_MARK_CONTEXT_MENU: 'custommarkcontextmenu',
    CUSTOM_VIEW_LOAD: 'customviewload',
    CUSTOM_VIEW_REMOVE: 'customviewremove',
    CUSTOM_VIEW_SAVE: 'customviewsave',
    CUSTOM_VIEW_SET_DEFAULT: 'customviewsetdefault',
    FILTER_CHANGE: 'filterchange',
    FIRST_INTERACTIVE: 'firstinteractive',
    FIRST_VIZ_SIZE_KNOWN: 'firstvizsizeknown',
    MARKS_SELECTION: 'marksselection',
    MARKS_HIGHLIGHT: 'markshighlight',
    PARAMETER_VALUE_CHANGE: 'parametervaluechange',
    STORY_POINT_SWITCH: 'storypointswitch',
    TAB_SWITCH: 'tabswitch',
    TOOLBAR_STATE_CHANGE: 'toolbarstatechange',
    URL_ACTION: 'urlaction',
    VIZ_RESIZE: 'vizresize',
  },
  ToolbarPosition: {
    TOP: 'top',
    BOTTOM: 'bottom',
  },
  ToolbarButtonName: {
    REDO: 'redo',
    UNDO: 'undo',
  },
  MenuType: {
    UBERTIP: 'ubertip',
  },
  Viz: () => {},
  _apiLoaded: true,
};
